import "server-only";

import { mkdir, readFile, rm, writeFile } from "fs/promises";
import os from "os";
import path from "path";
import { runNativeTool } from "@/lib/prepress/native-tool-runner";
import type { PrepressCheck } from "@/lib/prepress/types";

type GhostscriptInput = {
  sourcePdfBytes: Uint8Array;
  ghostscriptPath: string;
  cmykIccPath?: string;
};

type GhostscriptOutput = {
  bytes?: Uint8Array;
  checks: PrepressCheck[];
  notes: string[];
};

function pdfxDefinition() {
  return `%!\n/PDFX_def 10 dict def\nPDFX_def begin\n/Title (Printy business card PDF/X CMYK candidate)\n/Info (Generated by Printy Ghostscript prepress pipeline)\n/OutputConditionIdentifier (DeviceCMYK)\n/RegistryName (http://www.color.org)\n/Trapped /False\nend\n`;
}

export async function generateGhostscriptCmykPdfxCandidate(input: GhostscriptInput): Promise<GhostscriptOutput> {
  const tempDirectory = path.join(os.tmpdir(), `printy-prepress-${process.pid}-${Date.now()}`);
  const sourcePath = path.join(tempDirectory, "source.pdf");
  const outputPath = path.join(tempDirectory, "candidate.pdf");
  const pdfxDefinitionPath = path.join(tempDirectory, "PDFX_def.ps");

  await mkdir(tempDirectory, { recursive: true });
  await writeFile(sourcePath, input.sourcePdfBytes);
  await writeFile(pdfxDefinitionPath, pdfxDefinition(), "utf8");

  const args = [
    "-dSAFER",
    "-dBATCH",
    "-dNOPAUSE",
    "-dPDFX",
    "-dNOOUTERSAVE",
    "-dEmbedAllFonts=true",
    "-dSubsetFonts=true",
    "-dCompressFonts=true",
    "-dProcessColorModel=/DeviceCMYK",
    "-sColorConversionStrategy=CMYK",
    "-sDEVICE=pdfwrite",
    "-dCompatibilityLevel=1.4",
  ];

  if (input.cmykIccPath) {
    args.push(`-sDefaultCMYKProfile=${input.cmykIccPath}`, `-sOutputICCProfile=${input.cmykIccPath}`);
  }

  args.push(`-sOutputFile=${outputPath}`, pdfxDefinitionPath, sourcePath);

  try {
    const result = await runNativeTool(input.ghostscriptPath, args, 60000);

    if (result.exitCode !== 0) {
      return {
        checks: [{ name: "Ghostscript CMYK/PDFX candidate", status: "failed", message: result.stderr || result.stdout || "Ghostscript failed." }],
        notes: ["Ghostscript did not produce a CMYK PDF/X candidate."],
      };
    }

    const bytes = await readFile(outputPath).catch(() => undefined);

    if (!bytes) {
      return {
        checks: [{ name: "Ghostscript CMYK/PDFX candidate", status: "failed", message: "Ghostscript exited successfully but no output PDF was found." }],
        notes: ["Ghostscript output PDF was missing."],
      };
    }

    return {
      bytes,
      checks: [{ name: "Ghostscript CMYK/PDFX candidate", status: "passed", message: "Ghostscript generated a CMYK PDF/X candidate." }],
      notes: [input.cmykIccPath ? "Ghostscript used the configured CMYK ICC profile." : "Ghostscript used DeviceCMYK conversion without a configured ICC profile."],
    };
  } finally {
    await rm(tempDirectory, { recursive: true, force: true });
  }
}
